STOCK/STOCK/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyUser.urls')),
    path('', include('wallet.urls')),
    path('', include('WIG.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATICFILES_DIRS[0]}),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

STOCK/WIG/urls.py
from django.urls import path
from .views import init_data,update_WIG,Home,Analysis,update_Index,update_Currency,update_Wares,update_NC



urlpatterns = [
    path('init/', init_data,name='init_data'),
    path('update_NC/', update_NC,name='update_NC'),
    path('update_WIG/', update_WIG,name='update_WIG'),
    path('update_Index/', update_Index,name='update_Index'),
    path('update_Wares/', update_Wares,name='update_Wares'),
    path('update_Currency/', update_Currency,name='update_Currency'),
    path('', Home.as_view(),name='home'),
    path('Analysis', Analysis.as_view(),name='Analysis'),
    #path('Chart_data/<str:name>/', Chart_data.as_view(),name='Chart_data'),

]

STOCK/wallet/urls.py
from django.urls import path
from .views import wallet,Cash_Deposit,Cash_withdrawal,Lista_Bank_transfer,Cash_exchange,Get_Rate,Create_account,AccountDelete,Lista_Stocks,buy_stocks,buy_NC,autocomplete



urlpatterns = [
    path('wallet/', wallet.as_view() ,name='wallet'),
    path('Cash_Deposit/', Cash_Deposit.as_view() ,name='Cash_Deposit'),
    path('Cash_withdrawal/', Cash_withdrawal.as_view() ,name='Cash_withdrawal'),
    path('Lista_Bank_transfer/', Lista_Bank_transfer.as_view() ,name='Lista_Bank_transfer'),
    path('Cash_exchange/', Cash_exchange.as_view() ,name='Cash_exchange'),
    path('Create_account/', Create_account.as_view() ,name='Create_account'),
    path('AccountDelete/<int:pk>/', AccountDelete.as_view() ,name='AccountDelete'),
    path('Get_Rate/', Get_Rate ,name='Get_Rate'),
    path('Lista_Stocks/<int:pk>', Lista_Stocks.as_view() ,name='Lista_Stocks'),
    path('Lista_Stocks/<int:pk>/auto/', autocomplete ,name='autocomplete'),
    path('Lista_Stocks/<int:pk>/buy_stocks/<str:stock>/<str:genre>/', buy_stocks.as_view() ,name='buy_stocks'),

]

STOCK/wallet/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from WIG.models import CompanyData , Quotes_last , NCData,NC_Quotes_last

# Create your models here.
currency_choices= (
    ("USD", "USD"),
    ("EUR", "EUR"),
    ("GBP", "GBP"),
    ("PLN", "PLN")
    )
order = (
    ("Zakup","Zakup"),
    ("Sprzedarz","Sprzedarz")
)

class Currency_account(models.Model):
       
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    name = models.CharField(max_length=30)
    currency = models.CharField(max_length=9,
                  choices = currency_choices,
                  default="PLN")
    cash = models.FloatField(blank=True, null=True)
    average_exchange =  models.FloatField(blank=True, null=True)
    

    def __str__(self):
        return  str(self.name)





class Broker_account(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    name = models.CharField(max_length=30)
    cash = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=9,
                  choices = currency_choices,
                  default="PLN")

    def __str__(self):
        return  str(self.name)

class Stocks(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    stock = models.ForeignKey(CompanyData,on_delete=models.CASCADE)
    broker = models.ForeignKey(Broker_account,on_delete=models.CASCADE)
    price_buy = models.FloatField()
    amount = models.IntegerField()
    currency = models.CharField(max_length=9,
                  choices = currency_choices,
                  default="PLN")
    last_price = models.ForeignKey(Quotes_last,on_delete=models.CASCADE ,default = Quotes_last.objects.all().last().id)

    def acquisition_cost(self):
        return  self.price_buy  *self.amount

    def worth(self):
        return self.last_price.Closing_price * self.amount

    def profit(self):
        
        return  self.worth() - self.acquisition_cost()
    def profit_pr (self):
        return (self.worth() - self.acquisition_cost())/self.acquisition_cost()*100

    def __str__(self):
        return  str(self.stock)

class NC(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    stock = models.ForeignKey(NCData,on_delete=models.CASCADE)
    broker = models.ForeignKey(Broker_account,on_delete=models.CASCADE)
    price_buy = models.FloatField()
    amount = models.IntegerField()
    currency = models.CharField(max_length=9,
                  choices = currency_choices,
                  default="PLN")
    last_price = models.ForeignKey(NC_Quotes_last,on_delete=models.CASCADE ,default = Quotes_last.objects.all().last().id)

    def acquisition_cost(self):
        return  self.price_buy  *self.amount

    def worth(self):
        return self.last_price.Closing_price * self.amount

    def profit(self):
        
        return  self.worth() - self.acquisition_cost()
    def profit_pr (self):
        return (self.worth() - self.acquisition_cost())/self.acquisition_cost()*100

    def __str__(self):
        return  str(self.stock)

class Stocks_transfer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    stock = models.ForeignKey(CompanyData,on_delete=models.CASCADE)
    broker = models.ForeignKey(Broker_account,on_delete=models.CASCADE)
    price = models.FloatField()
    ammount = models.IntegerField(default=1)
    order = models.CharField(max_length=9,
                  choices = order,
                  default="Zakup")
    cash_after_broker = models.FloatField(blank=True, null=True)
    day_transfer = models.DateField( auto_now=False, auto_now_add=False)

class NC_transfer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    stock = models.ForeignKey(NCData,on_delete=models.CASCADE)
    broker = models.ForeignKey(Broker_account,on_delete=models.CASCADE)
    price = models.FloatField()
    ammount = models.IntegerField(default=1)
    order = models.CharField(max_length=9,
                  choices = order,
                  default="Zakup")
    cash_after_broker = models.FloatField(blank=True, null=True)
    day_transfer = models.DateField( auto_now=False, auto_now_add=False)

class broker_transfer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    account = models.ForeignKey("Currency_account",on_delete=models.CASCADE )
    account_broker = models.ForeignKey("Broker_account",on_delete=models.CASCADE )
    cash = models.FloatField(blank=True, null=True)
    title = models.TextField(max_length=400,blank=True, null=True)
    cash_after = models.FloatField(blank=True, null=True)
    cash_after_broker = models.FloatField(blank=True, null=True)
    day_transfer = models.DateField( auto_now=False, auto_now_add=False)

    def __str__(self):
        return   str(self.user)

class Bank_transfer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    account = models.ForeignKey("Currency_account",on_delete=models.CASCADE )
    cash = models.FloatField(blank=True, null=True)
    title = models.TextField(max_length=400,blank=True, null=True)
    cash_after = models.FloatField(blank=True, null=True)
    day_transfer = models.DateField( auto_now=False, auto_now_add=False)

    def __str__(self):
        return   str(self.user)



class Cantor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE )
    day_transfer = models.DateField( auto_now=False, auto_now_add=False)
    currency_account_to = models.ForeignKey("Currency_account",related_name="currency_account_to", on_delete=models.CASCADE )
    currency_account_for = models.ForeignKey("Currency_account",related_name="currency_account_for",on_delete=models.CASCADE )
    cash_to = models.FloatField(blank=True, null=True)
    cash_for = models.FloatField(blank=True, null=True)
    exchange_rate = models.FloatField(blank=True, null=True)
    cash_after = models.FloatField(blank=True, null=True)
    cash_after_for = models.FloatField(blank=True, null=True)
    exchange_rate_after = models.FloatField(blank=True, null=True)

    def __str__(self):
        return  str(self.currency_account_to) + str(self.cash_to) + str(self.day_transfer)

STOCK/wallet/forms.py
from django import forms 
from .models import  Currency_account,Bank_transfer,Cantor,NC_transfer
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

def get_question_form(conditional_model):
    class NC_transfer_form(forms.ModelForm):
        class Meta:
    
            model = conditional_model
            fields = ["order","price","ammount","day_transfer"]

        def __init__(self,broker_id,stock, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.broker_id = broker_id
            self.stock = stock.first()
            
            if not self.stock:

                self.fields['order'].choices=[('Zakup','Zakup')]

            self.fields['day_transfer'].widget.attrs.update({'autocomplete': 'off'})

        def clean(self,**kwargs):

            cleaned_data = super().clean()
            order = cleaned_data.get('order')
            ammount =cleaned_data.get('ammount')

            price =cleaned_data.get('price')

            if ammount == 0:
                msg = "Ilość musi być większa niż 0"
                self.add_error('ammount', msg)
            if price == 0:
                msg = "Cena musi być większa niż 0"
                self.add_error('price', msg)

            if order == "Zakup":
                if self.broker_id.cash < ammount*price:

                    raise ValidationError(
                        "Za mało środków na koncie"

                    )

            if  self.stock:
                if order == "Sprzedarz":
                    
                    if ammount > self.stock.amount:
                        raise ValidationError(
                            mark_safe("Za mało akcji na koncie.<br/>Zmniejsz ilość akcji na sprzedarz")
                        )

    return NC_transfer_form
        

STOCK/templates/wallet/History_date.html
{% extends 'basePanel.html' %} {% load static %}

{% block nav %}
	{% if request.user.is_authenticated %}
        <a class="right-topbar-item " href="{% url 'wallet' %}">Portfel</a>
		<a class="right-topbar-item " href="{% url 'home' %}">Notowania</a>
	{% endif %}
{% endblock nav %}


{% block content %}

<div class="training-container" >
    <div class="profilemenu">
        
        <div class="divQuotes" id="PLAN_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="PLAN"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >PLAN</button>
                        
            </form> 

        </div>
        <div class="divQuotes" id="Observe_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="Obserwowane"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >Obserwowane</button>
                        
            </form> 

        </div>
    </div>
    {% if listaBankTransfer %}
    <div class="border_middle" >
    {% else %}
    <div class="border_middle" style= "height:500px">
    {% endif %}
        <div class = "center_history">
            <form method="GET" action="{% url 'Lista_Bank_transfer' %}">
                {% csrf_token %}
                <div style="padding-left: 3%;">
                    <h3 >Wybierz zakres dat </h3>
                </div>
                
                <div style="display: flex;width: 100%;">
                    <div class = "filtrdate">
                        <div>
                            <span style="font-size: 19px">od:</span>
                        </div>
                        <div class="input-center">
                            <input id="date-since"  name = "date-since" type="text" autocomplete="off">
                        </div>
                    
                    </div >
                    <div class = "filtrdate">
                        <div >
                            <span style="font-size: 19px" >do</span>
                        </div>
                        <div class="input-center"> 
                            <input id="date-to" name="date-to" type="text" autocomplete="off">
                        </div>
                    </div>
                    <div  style = "display: block;padding-top: 37px;width: 20%;">
                  
                        <div >
                            <button type="submit"   class=" btn-primary-account"  >Filtuj</button>
                        </div>
                    </div>
                
                </div>
                
            
            </form>

        </div>
        <div>
        {% if listaBankTransfer %}
            <div class ="center-history-table">
                <table id="" class="table table-vcenter table-condensed table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center">
                                <div class="table-filter">
                                    <span> Nazwa konta</span>
                                </div>
                            </th>
                            <th class="text-center">
                                <div class="table-filter">
                                    <span> Tytuł przelewu</span>
                                </div>
                            </th>
                            <th class="text-center">
                                <div class="table-filter">
                                    <span> Data</span>
                                </div>
                            </th>
                            <th class="text-center">
                                <div class="table-filter">
                                    <span> Kwota</span>
                                </div>
                            </th>
                            <th class="text-center">
                                <div class="table-filter">
                                    <span> Stan Konta</span>
                                </div>
                            </th>
                            {% if exchange %}
                                <th class="text-center">
                                    <div class="table-filter">
                                        <span> Średni kurs</span>
                                    </div>
                                </th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for x in listaBankTransfer %}
                            {% if exchange %}
                                <tr>
                                    <td class="text-center" style="font-weight:bold;color: #555405" > {{x.currency_account_to}}</td>
                                    <td class="text-center" style="font-weight:bold;color: #555405" > Wymiana :{{x.cash_for}}/{{x.currency_account_for.currency}} na {{x.cash_to}}/{{x.currency_account_to.currency}}</td>
                                    <td class="text-center" style="font-weight:bold;color: #555405" > {{x.day_transfer}}</td>
                                    <td class="text-center cash" style="font-weight:bold;color: #555405" > {{x.cash_to}} {{x.currency_account_to.currency}}</td>
                                    <td class="text-center" style="font-weight:bold;color: #555405" > {{x.cash_after}} {{x.currency_account_to.currency}}</td>
                                    <td class="text-center" style="font-weight:bold;color: #555405" > {{x.exchange_rate_after|floatformat:2}} {{x.currency_account_for.currency}}/{{x.currency_account_to.currency}}</td>
                                </tr>

                            {% else %}
                                {% if x.account %}
                                    <tr>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > {{x.account}}</td>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > {{x.title}}</td>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > {{x.day_transfer}}</td>
                                        <td class="text-center cash" style="font-weight:bold;color: #555405" > {{x.cash}}</td>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > {{x.cash_after}}</td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > {{x.currency_account_for}}</td>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > Wymiana :{{x.cash_for}}/{{x.currency_account_for.currency}} na {{x.cash_to}}/{{x.currency_account_to.currency}}</td>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > {{x.day_transfer}}</td>
                                        <td class="text-center cash" style="font-weight:bold;color: #555405" > {{x.cash_for}}</td>
                                        <td class="text-center" style="font-weight:bold;color: #555405" > {{x.cash_after_for}}</td>
                                    </tr>
                                
                                
                                {% endif %}
                            {% endif %}


                {% endfor %}
        {% else %}
            <div style="margin-left:20%;width:60%;padding-left:3%">
                <h5>brak danych w danym kryterium proszę wybrać zakres dat</h1>
            
            </div>
        {% endif %}

        
        </div>
    </div>
 </div>
{% endblock content %}
{% block extra_js %}
    <script>
        $(function () {
            $("#date-since").datepicker({
                format:'yyyy-mm-dd',
            });
            $("#date-to").datepicker({
                format:'yyyy-mm-dd',
            });

        });
        let cash = document.getElementsByClassName("cash")
        console.log(cash)

        Array.prototype.map.call(cash, (x)=>{
            if (parseFloat(x.textContent.replace(/,/g, '.')).toFixed(2)< 0){
                x.classList.toggle("cash_W")
            }
        })



    </script>


{% endblock extra_js %}

STOCK/templates/wallet/buy_stocks.html
{% extends 'basePanel.html' %} {% load static %}

{% block nav %}
	{% if request.user.is_authenticated %}
        <a class="right-topbar-item " href="{% url 'wallet' %}">Portfel</a>
		<a class="right-topbar-item " href="{% url 'home' %}">Notowania</a>
	{% endif %}
{% endblock nav %}


{% block content %}

<div class="training-container" >
    <div class="profilemenu">
        
        <div class="divQuotes" id="PLAN_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="PLAN"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >PLAN</button>
                        
            </form> 

        </div>
        <div class="divQuotes" id="Observe_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="Obserwowane"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >Obserwowane</button>
                        
            </form> 

        </div>
    </div>
    <div class="border_middle">
        <div class = "center_cash">
            <form method="POST" action='.'>
                {% csrf_token %}
                <h1>{{title_account}} Operacja: </h1>
      
                <div class="input-center"> 
                    {{form.order}}
                    {{form.order.errors}}
                </div>

                <div>
                    <span style="font-size: 19px">Firma:</span>
                </div>
                <div class="text-center"> 
                    <h4 style="color:#70b97b;">{{stock}}</h4>
                </div>
                {% if amount.amount %}
                    <div>
                        <span style="font-size: 19px">ilość Akcji na koncie:</span>
                    </div>
                    <div class="text-center"> 
                        <h5 style="color:#a5611c;">{{amount.amount}} szt.</h5>
                    </div>
                    <div>
                        <span style="font-size: 19px">Cena kupna:</span>
                    </div>
                    <div class="text-center"> 
                        <h5 style="color:#a5611c;">{{amount.price_buy}} {{amount.currency}}</h5>
                    </div>
                
                
                {% endif %}
                <div>
                    <span style="font-size: 19px">Środki na koncie:</span>
                </div>
                <div class="text-center"> 
                    <h5 style="color:#a5611c;">{{broker.cash}} {{broker.currency}}</h5>
                    {{ form.non_field_errors }}
                </div>
                

                <div >
                    <span style="font-size: 19px" >Ilość</span>
                </div>
                <div class="input-center"> 
                    {{form.ammount}}
                    <div class="text-center"> 
                        {{form.ammount.errors}}
                    </div>
                </div>
                <div >
                    <span style="font-size: 19px" >Cena</span>
                </div>
                <div class="input-center"> 
                    {{form.price}}
                    <div class="text-center"> 
                        {{form.price.errors}}
                    </div>
                </div>
                <div >
                    <span style="font-size: 19px" >Wybierz datę</span>
                </div>
                <div class="input-center">
                    {{form.day_transfer}}
                    {{form.day_transfer.errors}}
                </div>
                <div class="text-center">
                    <button type="submit"   class=" btn-primary-account"  >wyślij transakcję</button>
                </div>
            
            </form>
            <div class="text-center">
                    <button onclick="location.href='{% url 'Lista_Stocks' pk=view.kwargs.pk %}'" class="btn-primary-cancel" >Anuluj</button>
            </div>
        </div>
    </div>
 </div>
{% endblock content %}
{% block extra_js %}
    <script>
        $(function () {
            $("#id_day_transfer").datepicker({
                format:'yyyy-mm-dd',
            });
        });



    </script>


{% endblock extra_js %}

STOCK/templates/wallet/cashdeposit.html
{% extends 'basePanel.html' %} {% load static %}

{% block nav %}
	{% if request.user.is_authenticated %}
        <a class="right-topbar-item " href="{% url 'wallet' %}">Portfel</a>
		<a class="right-topbar-item " href="{% url 'home' %}">Notowania</a>
	{% endif %}
{% endblock nav %}


{% block content %}

<div class="training-container" >
    <div class="profilemenu">
        
        <div class="divQuotes" id="PLAN_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="PLAN"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >PLAN</button>
                        
            </form> 

        </div>
        <div class="divQuotes" id="Observe_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="Obserwowane"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >Obserwowane</button>
                        
            </form> 

        </div>
    </div>
    <div class="border_middle">
        <div class = "center_cash">
            <form method="POST" action='.'>
                {% csrf_token %}
                <h1>{{title_account}} na konto: </h1>
                <div class="text-center">
                    <h3 style="color:#70b97b;">{{account}}</h3>
                </div>
                <div>
                    <span style="font-size: 19px">Kwota</span>
                </div>
                <div class="input-center">
                    {{form.cash}}
                    {{form.cash.errors}}
                </div>
                <div >
                    <span style="font-size: 19px" >Tytuł</span>
                </div>
                <div class="input-center"> 
                    {{form.title}}
                    {{form.title.errors}}
                </div>
                <div >
                    <span style="font-size: 19px" >Wybierz datę</span>
                </div>
                <div class="input-center">
                    {{form.day_transfer}}
                    {{form.day_transfer.errors}}
                </div>
                <div class="text-center">
                    <button type="submit"   class=" btn-primary-account"  >wyślij przelew</button>
                </div>
            
            </form>
            <div class="text-center">
                    <button onclick="location.href='{% url 'wallet' %}'" class="btn-primary-cancel" >Anuluj</button>
            </div>
        </div>
    </div>
 </div>
{% endblock content %}
{% block extra_js %}
    <script>
        $(function () {
            $("#id_day_transfer").datepicker({
                format:'yyyy-mm-dd',
            });
        });



    </script>


{% endblock extra_js %}

STOCK/templates/wallet/create_account.html
{% extends 'basePanel.html' %} {% load static %}

{% block nav %}
	{% if request.user.is_authenticated %}
        <a class="right-topbar-item " href="{% url 'wallet' %}">Portfel</a>
		<a class="right-topbar-item " href="{% url 'home' %}">Notowania</a>
	{% endif %}
{% endblock nav %}


{% block content %}

<div class="training-container" >
    <div class="profilemenu">
        
        <div class="divQuotes" id="PLAN_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="PLAN"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >PLAN</button>
                        
            </form> 

        </div>
        <div class="divQuotes" id="Observe_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="Obserwowane"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >Obserwowane</button>
                        
            </form> 

        </div>
    </div>
    <div class="border_middle">
        <div class = "center_cash">
            <form method="POST" action='.'>
                {% csrf_token %}
                <h2> Otwórz nowe konto: </h2>
        
                <div>
                    <span style="font-size: 19px">Nazwa konta</span>
                </div>
                <div class="input-center">
                    {{form.name}}
                    {{form.name.errors}}
                </div>
                <div >
                    <span style="font-size: 19px" >Waluta</span>
                </div>
                <div class="input-center"> 
                    {{form.currency}}
                    {{form.currency.errors}}
                </div>

                <div class="text-center">
                    <button type="submit"   class=" btn-primary-account"  >Otwórz konto</button>
                </div>
            
            </form>
            <div class="text-center">
                    <button onclick="location.href='{% url 'wallet' %}'" class="btn-primary-cancel" >Anuluj</button>
            </div>
        </div>
    </div>
 </div>
{% endblock content %}
{% block extra_js %}
    <script>
        $(function () {
            $("#id_day_transfer").datepicker({
                format:'yyyy-mm-dd',
            });
        });



    </script>


{% endblock extra_js %}

STOCK/templates/wallet/delete_account.html
{% extends 'basePanel.html' %} {% load static %}

{% block nav %}
	{% if request.user.is_authenticated %}
        <a class="right-topbar-item " href="{% url 'wallet' %}">Portfel</a>
		<a class="right-topbar-item " href="{% url 'home' %}">Notowania</a>
	{% endif %}
{% endblock nav %}


{% block content %}

<div class="training-container" >
    <div class="profilemenu">
        
        <div class="divQuotes" id="PLAN_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="PLAN"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >PLAN</button>
                        
            </form> 

        </div>
        <div class="divQuotes" id="Observe_btn">

            <form action="." method="GET" >
                {% csrf_token %}

                <input type="text" name="quotes" value="Obserwowane"  style="display:None;">
                <button type="submit"   class="buttonQuotes"  >Obserwowane</button>
                        
            </form> 

        </div>
    </div>
    <div class="border_middle">
        <div class = "center_cash">
            <form method="POST" action='.'>
               <form method="post">{% csrf_token %}
                    <p style="text-align: center;padding: 50px 0;">Czy chcesz usunąć "{{ object }}"?</p>


                <div class="text-center">
                    <button type="submit"   class=" btn-primary-account"  >Usuń  konto</button>
                </div>
            
            </form>
            <div class="text-center">
                    <button onclick="location.href='{% url 'wallet' %}'" class="btn-primary-cancel" >Anuluj</button>
            </div>
        </div>
    </div>
 </div>
{% endblock content %}
{% block extra_js %}
    <script>
        $(function () {
            $("#id_day_transfer").datepicker({
                format:'yyyy-mm-dd',
            });
        });



    </script>


{% endblock extra_js %}